modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "BSD-3"

[[mods]]
modId = "contact"
version = "${version}"
displayName = "Contact"
authors = "Flechazo, RoshioLeo, Gloridifice, MalayP"
description = 'A mod that provides postal service'

logoFile = "assets/contact/logo.png"

[[dependencies.contact]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.contact]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.contact]]
modId = "oelib"
mandatory = true
versionRange = "[0.2.0,)"
ordering = "AFTER"
side = "BOTH"