modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "BSD-3"

[[mods]]
modId = "contact"
version = "${version}"
displayName = "Contact"
authors = "Flechazo, RoshioLeo, Gloridifice, MalayP"
description = 'A mod that provides postal service'

logoFile = "assets/contact/logo.png"

[[dependencies.contact]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.contact]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.contact]]
modId = "oelib"
mandatory = true
versionRange = "[0.0.7-beta,)"
ordering = "AFTER"
side = "BOTH"

